 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamesport.Vista;

/**
 *
 * @author javam
 */
public class frmProveedorGuardar extends javax.swing.JPanel {

    /**
     * Creates new form frmTurno
     */
    public frmProveedorGuardar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panPrincipal = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1570, 800));
        setLayout(new java.awt.GridBagLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText("Nombre");
        panPrincipal.add(lblNombre);
        lblNombre.setBounds(340, 40, 100, 14);

        lblNit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNit.setText("Nit");
        panPrincipal.add(lblNit);
        lblNit.setBounds(360, 100, 60, 14);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        panPrincipal.add(btnGuardar);
        btnGuardar.setBounds(580, 390, 120, 40);

        lblTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefono.setText("Telefono");
        panPrincipal.add(lblTelefono);
        lblTelefono.setBounds(340, 160, 80, 14);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email");
        panPrincipal.add(lblEmail);
        lblEmail.setBounds(360, 220, 60, 14);

        lblDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDireccion.setText("Direccion");
        panPrincipal.add(lblDireccion);
        lblDireccion.setBounds(350, 280, 90, 14);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panPrincipal.add(txtNombre);
        txtNombre.setBounds(420, 30, 220, 40);

        txtNit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panPrincipal.add(txtNit);
        txtNit.setBounds(420, 90, 220, 40);

        try {
            txtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panPrincipal.add(txtTelefono);
        txtTelefono.setBounds(420, 150, 220, 40);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panPrincipal.add(txtEmail);
        txtEmail.setBounds(420, 210, 220, 40);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panPrincipal.add(txtDireccion);
        txtDireccion.setBounds(420, 270, 220, 40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 979;
        gridBagConstraints.ipady = 579;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 1, 33);
        add(panPrincipal, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panPrincipal;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtNit;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
